groups:
- name: zal
  rules:
  - alert: MCDRebootError
    annotations:
      message: Reboot failed on {{ $labels.node }} , update may be blocked
    expr: |
      mcd_reboot_err > 0
    labels:
      severity: critical
- name: mcd-drain-error
  rules:
  - alert: MCDDrainError
    annotations:
      message: 'Drain failed on {{ $labels.node }} , updates may be blocked. For
        more details:  oc logs -f -n openshift-machine-config-operator machine-config-daemon-<hash>
        -c machine-config-daemon'
    expr: |
      mcd_drain > 0
    labels:
      severity: warning
- name: mcd-pivot-error
  rules:
  - alert: MCDPivotError
    annotations:
      message: 'Error detected in pivot logs on {{ $labels.node }} '
    expr: |
      mcd_pivot_err > 0
    labels:
      severity: warning
- name: mcd-kubelet-health-state-error
  rules:
  - alert: KubeletHealthState
    annotations:
      message: Kubelet health failure threshold reached
    expr: |
      mcd_kubelet_state > 2
    labels:
      severity: warning
- name: system-memory-exceeds-reservation
  rules:
  - alert: SystemMemoryExceedsReservation
    annotations:
      message: System memory usage of {{ $value | humanize }} on {{ $labels.node
        }} exceeds 90% of the reservation. Reserved memory ensures system processes
        can function even when the node is fully allocated and protects against
        workload out of memory events impacting the proper functioning of the node.
        The reservation may be increased (https://docs.openshift.com/container-platform/latest/nodes/nodes/nodes-nodes-managing.html)
        when running nodes with high numbers of pods.
    expr: |
      sum by (node) (container_memory_rss{id="/system.slice"}) > ((sum by (node) (kube_node_status_capacity{resource="memory"} - kube_node_status_allocatable{resource="memory"})) * 0.9)
    labels:
      severity: warning
